/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Date = IDL.Int;
export const HabitId = IDL.Int;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Execution = IDL.Int;
export const HabitView = IDL.Record({
  'id' : HabitId,
  'created' : Date,
  'executions' : IDL.Vec(Execution),
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createHabit' : IDL.Func([IDL.Text, Date], [HabitId], []),
  'deleteHabit' : IDL.Func([HabitId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHabit' : IDL.Func([HabitId], [HabitView], ['query']),
  'getHabits' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(HabitId, HabitView))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markComplete' : IDL.Func([HabitId, Date], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unmarkComplete' : IDL.Func([HabitId, Date], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Date = IDL.Int;
  const HabitId = IDL.Int;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Execution = IDL.Int;
  const HabitView = IDL.Record({
    'id' : HabitId,
    'created' : Date,
    'executions' : IDL.Vec(Execution),
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createHabit' : IDL.Func([IDL.Text, Date], [HabitId], []),
    'deleteHabit' : IDL.Func([HabitId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHabit' : IDL.Func([HabitId], [HabitView], ['query']),
    'getHabits' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(HabitId, HabitView))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markComplete' : IDL.Func([HabitId, Date], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unmarkComplete' : IDL.Func([HabitId, Date], [], []),
  });
};

export const init = ({ IDL }) => { return []; };